//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomTerraria.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomTerraria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahole
        ///anus
        ///ash0le
        ///ash0les
        ///asholes
        ///ass
        ///Ass Monkey
        ///Assface
        ///assh0le
        ///assh0lez
        ///asshole
        ///assholes
        ///assholz
        ///asswipe
        ///azzhole
        ///bassterds
        ///bastard
        ///bastards
        ///bastardz
        ///basterds
        ///basterdz
        ///Biatch
        ///bitch
        ///bitches
        ///Blow Job
        ///boffing
        ///butthole
        ///buttwipe
        ///c0ck
        ///c0cks
        ///c0k
        ///Carpet Muncher
        ///cawk
        ///cawks
        ///Clit
        ///cnts
        ///cntz
        ///cock
        ///cockhead
        ///cock-head
        ///cocks
        ///CockSucker
        ///cock-sucker
        ///crap
        ///cum
        ///cunt
        ///cunts
        ///cuntz
        ///dick
        ///dild0
        ///dild0s
        ///dildo
        ///dildos
        ///dilld0
        ///dilld0s
        ///dominatricks
        ///dominatrics
        ///dominatrix
        ///dyke
        ///enema        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string badwords {
            get {
                return ResourceManager.GetString("badwords", resourceCulture);
            }
        }
        
        internal static byte[] Combat_Crit {
            get {
                object obj = ResourceManager.GetObject("Combat_Crit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Combat_Text {
            get {
                object obj = ResourceManager.GetObject("Combat_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Death_Text {
            get {
                object obj = ResourceManager.GetObject("Death_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Item_Stack {
            get {
                object obj = ResourceManager.GetObject("Item_Stack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mouse_Text {
            get {
                object obj = ResourceManager.GetObject("Mouse_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
